---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: solixdevops3/solixcdp3-redis:v3.1
        imagePullPolicy: Always
        command: ["redis-server", "--appendonly", "no", "--requirepass", "nies-hgub-pdkw"]
        #command: ["/bin/sh","-c"]
          #args: ["redis-server --appendonly yes; redis-server --cluster-enabled yes"]
        ports:
        - containerPort: 6379
        # readinessProbe:
          # periodSeconds: 10
          # tcpSocket:
            # port: 6379
        # livenessProbe:
          # periodSeconds: 10
          # tcpSocket:
            # port: 6379
      imagePullSecrets:
      - name: solixdevops3
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    nodePort: 30303
    targetPort: 6379