---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-tenant
spec:
  selector:
    matchLabels:
      app: ui-tenant
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ui-tenant
    spec:
      containers:
      - name: ui-tenant
        image: solixdevops3/solixcdp3-ui-tms:v3.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        volumeMounts:                 # indicates which Volume (from spec.template.spec.volumes) should be used
          - name: scdp-ui-configmap-volume
            mountPath: /opt/build/env/env-config.js
            subPath: env-config.js
      volumes:
        - name: scdp-ui-configmap-volume
          configMap:
            name: scdp-ui-configmap
      imagePullSecrets:
      - name: solixdevops3
---
apiVersion: v1
kind: Service
metadata:
  name: ui-tenant
spec:
  type: NodePort
  selector:
    app: ui-tenant
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 32323