---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: solixdevops3/solixcdp3-ui:v3.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        volumeMounts:                 # indicates which Volume (from spec.template.spec.volumes) should be used
          - name: scdp-ui-configmap-volume
            mountPath: /opt/build/env/env-config.js
            subPath: env-config.js
      volumes:
        - name: scdp-ui-configmap-volume
          configMap:
            name: scdp-ui-configmap
      imagePullSecrets:
      - name: solixdevops3
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ui-ingress
spec:
  tls:
  - hosts:
      - appcdp.solixcorp.com
    secretName: scdp-tls-secret
  rules:
  - host: appcdp.solixcorp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 80  
  