---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: solixdevops3/solixcdp3-zipkin:v3.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9411
        #command: ["java","-jar","/opt/zipkin-server-2.19.3-exec.jar"]
        #readinessProbe:
        #  periodSeconds: 10
        #  tcpSocket:
        #    port: 9411
        #livenessProbe:
        #  periodSeconds: 10
        #  tcpSocket:
        #    port: 9411
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx4096m -Duser.timezone=GMT -Doracle.jdbc.timezoneAsRegion=false"
        envFrom:
          - configMapRef:
              name: scdp-configmap
        # resources:
          # limits:
            # memory: 256Mi
            # cpu: 125m
          # requests:
            # cpu: 70m
            # memory: 64Mi
      imagePullSecrets:
      - name: solixdevops3
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 31000